### ISSUE TITLE
MetaLookup replies with 400 OK

### ISSUE THREAD

**Issue by RMeissnerCC** [openeduhub/metalookup#133]
Information by Hupf, only screenshot so far:
![image](https://user-images.githubusercontent.com/50482279/178412133-09bafb3a-6407-4504-96ed-94c68f9268bd.png)

Ping and endpoint work for local to remote REST call.

**Comment by RMeissnerCC** [comment]
Connected to: https://issues.edu-sharing.net/jira/browse/KBMBF-532

**Comment by RMeissnerCC** [comment]
See https://issues.edu-sharing.net/jira/browse/KBMBF-532
According to the logs, the service was restarted later on. The relevant code is not present in dev branch code, anymore. Thus, it is probably "solved" by pulling the newest image.

**Comment by RMeissnerCC** [comment]
Another bug currently plaguing MetaLookup:

`Traceback (most recent call last):
  File "/home/extractor/features/accessibility.py", line 47, in _execute_api_call
    process = await session.get(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 913, in start
    self._continue = None
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 718, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
2022-07-13 12:18:43,287  ERROR   Unknown exception from extracting metadata: '(URL('/wiki/Datei:Curriculum_Vitae_of_Gabor_B._Racz.pdf'),)'. Traceback (most recent call last):
 `

**Comment by MRuecklCC** [comment]
This should be resolved via the last deployment after #136.
